### PR TITLE
Plan basics

### PR DESCRIPTION
**Pull request by fosterlynn**
Fixed up Plan with the contents of my PR over in VF, https://github.com/valueflows/valueflows/pull/501.  (PR there not merged, but it is going pretty slowly, and I think we can go with this for now.)

I think I missed the Plan mutations.  I think the rest is there, but please double-check @pospi .

### CODE REVIEW

**Comment by pospi** [comment]
Fixed up some bugs with that. I have some lingering questions:

- do intents factor in to plans at all? There aren't any relationships for them yet.
- why `nonWorkInputs` instead of just `inputs`? Could we have the generic case and filter on the input `action` instead? Or should there be a separate `workInputs`?

These two might be related: should `plannedNonWorkInputs` / `plannedOutputs` actually be pointing to `Intent`s, with `committedNonWorkInputs` / `committedOutputs` to match `Commitment`s? Or does all that stuff get handled by the underlying `Process`es which are part of the `Plan`?

**Comment by fosterlynn** [comment]
>do intents factor in to plans at all? There aren't any relationships for them yet.

Not directly, at least yet.  The relationship with commitment is only for the independent demand(s) of the plan.  There's one more relationship we have in NRP, but we're not sure we actually need it, so are leaving it off until we get some new experience with it.

>why nonWorkInputs instead of just inputs? Could we have the generic case and filter on the input action instead? Or should there be a separate workInputs?

Yes, we can do this generically, it was just to make things easier for the UI.  I guess  https://github.com/valueflows/vf-graphql/issues/15 was just agent-based queries.... we can do the same thing everywhere, and add enum kinds of things where we need them, or however you prefer to structure them.  For this one, filtering on action should be OK.  Do we need a "not"?  That's probably why I added the "nonWorkInputs".  Actually, I don't even remember the use case for "nonWorkInputs".... Let's not worry about it until we actually need it.

>These two might be related: should plannedNonWorkInputs / plannedOutputs actually be pointing to Intents, with committedNonWorkInputs / committedOutputs to match Commitments?

I think we should have intendedInputs, intendedOutputs, committedInputs, committedOutputs.  Think I saw them somewhere, but don't see the intent ones now.  Anyhow the term "planned" can refer to either Intents or Commitments.

**Comment by pospi** [comment]
I've kept with `plannedInputs` & `completedInputs` etc for now. I don't see how there can be `Intents` visible from `Plans` if there is no `independentDemandOf` field in `Intent`?

Also just wanted to check that those latest additions & names make sense from your point of view.

**Comment by fosterlynn** [comment]
>I've kept with plannedInputs & completedInputs etc for now. I don't see how there can be Intents visible from Plans if there is no independentDemandOf field in Intent?

You have to keep in mind that in a plan, some flows could be Intents and some could be Commitments.  So the independentDemandOf would be Commitments and some or all of the work could be Intents (that would be a common pattern for example in Sensorica where their policy is that people only can assign themselves to work).  Or they could have an Intent to purchase some components that they don't make themselves.  But they don't have doubts that those input Intents will become Commitments.

>completedInputs

Maybe observedInputs to be more consistent with the language?  Also people may log several events over time to fulfill a commitment, so things might not be so much "completed" at any point in time.

**Comment by pospi** [comment]
> You have to keep in mind that in a plan, some flows could be Intents and some could be Commitments.

That's what I'm saying... there is no linkage between `Plan` & `Intent` that I can see. I would have thought either:

1. `Intent` gets an `independentDemandOf` field as for `Commitment`; and `Plan.plannedInputs` returns a mixture of `Intent` & `Commitment`, or there is a new field added to `Plan` to query its input `Intent`s.
2. Those intents are located via the satisfactions linking from input `Commitment`s to `Intent`s.

Obviously option #2 is already doable, but I'm unclear on the order of behaviour there since `Commitment`s need to be input after their matching `Intent`s, and I would have expected that if `Intent`s play a role in `Plan`s they would be defined at the time of the `Plan`'s creation, meaning there will be times when `Intent`s are present but not `Commitment`s, making them unreachable.

Does that make sense?

**Comment by fosterlynn** [comment]
>>    You have to keep in mind that in a plan, some flows could be Intents and some could be Commitments.

>That's what I'm saying... there is no linkage between Plan & Intent that I can see.

The linkage between Plan and Intent, or for that matter between Plan and all the Commitments (there could be lots that aren't independent demand, which is the final outputs of the plan) goes through Process. You can get all the processes in a plan, and all the intents or commitments for the processes.  We'll see if that is reasonable in queries.

You can also trace backwards from each independent demand back through its value flows, but you have to be able to to tell when you reach the boundary of the plan, and the processes can do that.

>Those intents are located via the satisfactions linking from input Commitments to Intents.

You are right this is not a good way.

> and Plan.plannedInputs returns a mixture of Intent & Commitment

Looks like we need to fix that in any case. I'll make another commit to this PR.

**Comment by fosterlynn** [comment]
>> and Plan.plannedInputs returns a mixture of Intent & Commitment

>Looks like we need to fix that in any case. I'll make another commit to this PR.

Done.  I separated them, to keep it simple.  But it might also be useful to have plannedInputs/Outputs that return both intents and commitments.  I can add it if you think that makes sense.

**Comment by pospi** [comment]
Sorry, looks like I dropped the ball on this one. I've resolved the merge conflicts and am happy to merge this, but maybe we should leave some notes here for our future selves as to the current status of `Plan`? I see that you haven't taken away the comment about it not being in VF yet- so this is an experimental feature?

Actually, maybe we should put a description on the record type before merging. Any suggestions?

**Comment by fosterlynn** [comment]
I will do some cleanup on this today.  Descriptions and better note that yes, it is not accepted in VF.

**Comment by fosterlynn** [comment]
>I will do some cleanup on this today.

Done.  It was actually pretty behind, although the mutations seemed OK.  Please review @pospi ....

**Pull request merged**
