### PR TITLE
Definitions and VF changes

### PR DESCRIPTION
**Pull request by fosterlynn**
I combined the last 2 PRs, https://github.com/valueflows/vf-graphql/pull/47 and https://github.com/valueflows/vf-graphql/pull/48, which I will close after doing this one.  Fixed all merge conflicts, so this should merge more easily.  But still needs a good review @pospi and probably a compile check.

I'm going to use this one to create json-schema definitions, will come back here with anything I find that needs fixing from that exercise.

### CODE REVIEW

**Comment by pospi** [comment]
Merged, but I'm curious to hear more about these new fields for delineating resources: `effortQuantity`, `accountingQuantity`, `onHandQuantity` etc. Also with `unitBased`. Are we trying to push too much higher-order inference down into the data model? Can such distinctions be made by inferences further up the tree at all (eg. it's "effort" resource if `action == 'work'`)? Curious if this inference holds up or whether there are any other parallels; or if this signals a more fundamental shift in thinking or project scope.

Would also be good to get a primer on `Scenario`s as part of our next VF update call; but for those following externally would be great to have a short summary here too or link to the appropriate VF core issues as you did for the recent `Transfer` changes.

**Comment by pospi** [comment]
@fosterlynn there were quite a few syntax errors in that update (fixed now), and a conflict regarding the `independentDemandOf` description- please have a look over to make sure everything is as you expect and I will try to get a sense of correctness from the git logs. Really liking the new more detailed descriptions, they help a lot with readability!

**Comment by pospi** [comment]
I think it's good after looking through logs, I might have messed up `independentDemandOf` but have fiddled with it twice now so will leave it to you to put the correct description in.

`RecipeResource` is something I also don't yet understand the need for and would be good to have an overview of that when we next connect as well (:

**Comment by fosterlynn** [comment]
>there were quite a few syntax errors in that update (fixed now)

Sorry about that !!  I tried to catch you in chat to let you know that, but didn't succeed.  (I am seeing them when I'm creating json-schemas.)  Thanks for fixing, I'll take a look at all and check independentDemandOf.  And am making a list while I do the json-schema work, will fix all of them in one PR when I'm done.

**Pull request merged**
