### PR TITLE
add definitions

### PR DESCRIPTION
**Pull request by fosterlynn**
In process, please do not merge until complete.

### CODE REVIEW

**Comment by fosterlynn** [comment]
I think I have done all the .gql files.  I didn't do the commented out interfaces, let me know if I should.

Here are my notes of mis-matched properties.  Some of these are valid, conscious decisions to not allow direct create/update.  Some we need to fix.  I'm including all of them, for documentation, and so we can just take a minute and think about all of them.  Perhaps you can mark the ones you think are not a bug.  Then I can review and go in and fix the bugs.
* Agent definition missing primaryLocation .
* EconomicEvent missing atLocation and realizationOf in the definition.
* EconomicResourceUpdateParams missing name.
* EconomicResourceCreateParams missing classifiedAs, unitOfEffort.
* EconomicResource create and update missing accountingQuantity, onhandQuantity, stage, state.
* EconomicResource definition, EconomicResourceUpdateParams missing currentLocation.
* ProductBatch missing create and update.
* Process create and update missing basedOn, classifiedAs.
* Process definition missing plannedWithin.
* Commitment doesn't have update action, but EconomicEvent does.
* Commitment create and update missing created - seems OK I guess.
* Commmitment definition missing independentDemandOf, clauseOf, atLocation.
* Intent definition missint atLocation.
* Plan refinementOf is in the type def but not the create and input.
* ProposedIntent and ProposedTo don't have create or update (ProposedTo needs only create probably).
* Scenario create and update don't have refinementOf.
* ScenarioDefinition doesn't have name on update.
* RecipeResource update and create missing resourceConformsTo
* RecipeResource definition doesn't have stage or state.
* RecipeProcess create and update missing resourceConformsTo.

Also, I'm not set up to test these, so I'm leaving that to you @pospi with thanks!

**Comment by pospi** [comment]
Most of these are not bugs actually, so that's good! I documented this new behaviour at https://github.com/valueflows/vf-graphql/#code-structure but should have pointed you to it.

Did a pass at them so you don't have to do it twice. These from your above list still seem valid:

- [x] ProductBatch missing create and update. (also missing a delete mutation)
- [x] Process create and update missing basedOn, classifiedAs. Fine to add so long as they don't impact any accounting
- [x] Plan refinementOf is in the type def but not the create and input.
- [x] Scenario create and update don't have refinementOf.
- [x] ScenarioDefinition doesn't have name on update.
- [x] RecipeResource update and create missing resourceConformsTo
- [x] RecipeProcess create and update missing resourceConformsTo.

All other "missing field" errors are fine.

"Yes" to these- they were on my todo list but I'm more than happy to share the load!

- [x] Agent definition missing primaryLocation

Special cases to discuss:

- ProposedIntent and ProposedTo don't have create or update: no, they don't. They have the functional forms `proposeIntent()` and `proposeTo()` instead. I think we should follow the same pattern for `AgentRelationships`- instead of `(create|update|delete)AgentRelationship`, we could have the two `createAgentRelationship(subject: ID!, object: ID!, relationship: ID!, note: String)` and `deleteAgentRelationship(subject: ID!, object: ID!, relationship: ID!)`? I find this a cleaner form for handling such compound index records. There are probably other record types like this. Thoughts?
- RecipeResource definition doesn't have stage or state... should it? I wouldn't have thought those parameters would be relevant at the recipe layer?

Other stuff:

- I added a commit with some query method descriptions for Agent. Not sure if you will like them or not, but we need a swathe of those across all top-level queries and mutations as well. Feel free to open up to multi-line comments (delimited by `"""`) if you feel a need to document particular parameters or provide longer descriptions.

Fixed these already:

- Commitment doesn't have update action, but EconomicEvent does. Oh dear... something seems to have gone very wrong with EconomicEvent. Not sure why it was like that (traced it back a way through history but seems like maybe I just didn't loop back- changed it to the permissible fields for update).

**Comment by pospi** [comment]
Also, `primaryAccountable` is in #65, no? Feel free to merge that one into this if you wish

**Comment by fosterlynn** [comment]
Did some of the above.... either checked or documented below.

>Also, primaryAccountable is in #65, no? Feel free to merge that one into this if you wish

Forgot it wasn't there already.  Hand copied it over to this PR.

>RecipeResource definition doesn't have stage or state... should it? I wouldn't have thought those parameters would be relevant at the recipe layer?

Yes it should.  Like, a document can only be proofread once it is edited - input "edited document", output "proofread document".  It becomes part of the logical identifier.

>ProposedIntent and ProposedTo don't have create or update: no, they don't. They have the functional forms proposeIntent() and proposeTo() instead.

Thinking about this.  I find it a bit confusing, since they are still separate mutations; might seem more right if you were creating the ProposedIntent at the same time as the Intent?  In the case of agent relationships, they will usually be created at a totally different time than the agents, leaving it feeling even more odd that it has a different format you have to remember.  But I understand they are all resolving M:M relationships, and leave the decision up to you.  (It is basically a graphql decision, and I've never coded graphql in a UI.)

**Comment by pospi** [comment]
I'm so grateful for you doing this! Looks perfect, flicking through the diff (:

RE the functional form for the smaller "relational" records, one of the reasons I like it is that it reduces the API surface for those record types down to two calls (CREATE/DELETE), rather than including an update. But thinking about it now- for things like `AgentRelationshipRole`, you probably *do* want an UPDATE in order to keep existing links intact, so I'm not sure. Maybe we should stick to a uniform RESTful pattern for most mutations?

I'm also looking at the `ID` field types in the `input` structs and lamenting that those don't have information on the linking type. What do you think is the best way of indicating that? Is there a repeatable pattern we can apply like...

```

"(`SpatialThing`) The main place an agent is located, often an address where activities occur and mail can be sent. This is usually a mappable geographic location.  It also could be a website address, as in the case of agents who have no physical location."
primaryLocation: ID
```

thoughts?

**Comment by fosterlynn** [comment]
> for things like AgentRelationshipRole, you probably do want an UPDATE in order to keep existing links intact

That is quite probable, especially as we get things like dates and/or status of a relationship.  (I know we need one or the other, maybe both.)

> Maybe we should stick to a uniform RESTful pattern for most mutations?

Seems simplest, which is worth something (again noting you are way closer to this code base).  AgentRelationshipRole has more content of its own than some of the others, which simply resolve a M:M.  Although, Fulfillment and Satisfaction also have content of their own.  The proposal stuff, not so much, although that is untried in a real use case, where AgentRelationshipRole has been in enough implementations to have proven itself pretty well.

**Comment by pospi** [comment]
Ok, I'm done touching for now. Finished off the odds and ends that have come up above. Still to do:

- [ ] Decide on how to address generic state (see [this comment](https://github.com/valueflows/valueflows/pull/611#issuecomment-591717030)). Or, we could leave that out of the spec for now, and say that `state` is readonly and can only be altered by domain-specific logic? Your call.
- [ ] Add descriptions for top-level mutations & queries (see attempts started in `agent.gql`)- do we want to bite this off now, or just finish something "minimum acceptable" for Agent and do the remainder in a future update?
- [ ] Decide on a format for indicating the destination types to which `ID` fields should refer in `input` types, and document these.

**Comment by fosterlynn** [comment]
>Decide on a format for indicating the destination types to which ID fields should refer in input types, and document these.

Not sure what is meant?  I see you maybe started putting like `object: ID! # Agent`.  Is that it?  How does that show up to the dev writing graphql?

>Add descriptions for top-level mutations & queries (see attempts started in agent.gql)- do we want to bite this off now, or just finish something "minimum acceptable" for Agent and do the remainder in a future update?

I'm not sure they are that useful?  At least the normal 'agent', 'allAgents' stuff.  Would be good to define the possibly unclear ones, maybe even all the "# inverse relationships and queries" ones.  It can wait though imo.  If you want, I can tackle that in spare moments in a new PR.

>Decide on how to address generic state (see this comment). Or, we could leave that out of the spec for now, and say that state is readonly and can only be altered by domain-specific logic? Your call.

Hmmm.  Maybe safer to do the latter for now, so it is not just wide open.

**Comment by pospi** [comment]
> I see you maybe started putting like object: ID! # Agent. Is that it? How does that show up to the dev writing graphql?

Yep- that doesn't show up- we need to figure a way to put it in the field description strings.

> If you want, I can tackle that in spare moments in a new PR.

Always grateful to have better documentation (:

**Comment by pospi** [comment]
@fosterlynn I think I want to push this through, because it means I can do a bunch of missing-field updates and get the Holochain implementation aligned, which opens me up to doing UI work.

So, let's leave top-level query & mutation documentation until next point release and maybe just go ahead with the ID type documenting for input types as per my above suggestion? (ie. prefixing the line with "`(TypeName)`" in order to indicate the expected foreign key type)

**Comment by fosterlynn** [comment]
>I think I want to push this through

:+1: 

>So, let's leave top-level query & mutation documentation until next point release and maybe just go ahead with the ID type documenting for input types as per my above suggestion?

Sounds good.  Feel free to merge this without, and we can do a separate PR.  (Not sure if I can get to it today, but soon.)

**Pull request merged**
